import type { Review } from '../types'

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    userId: 'user-1',
    roomId: 'room-1',
    rating: 4,
    summary: '퍼즐 구성이 탄탄하고 스토리 몰입감이 좋았다',
    subMetrics: {
      puzzleQuality: 5,
      storyDirection: 4,
      setQuality: 4,
      horror: 2,
      puzzleDifficulty: 4,
      clearDifficulty: 3,
    },
    visitMeta: {
      isSuccess: true,
      remainingMinutes: 5,
      headcount: 4,
      genreTags: ['추리', '미스터리'],
      customGenre: null,
      wouldRevisit: true,
    },
    visitedAt: '2026-02-15',
    body: '전체적으로 완성도가 높은 테마. 힌트 없이 클리어 가능한 난이도.',
    photos: [],
    visibility: 'link',
    shareToken: 'mock-token-abc123',
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-02-15T10:00:00Z',
  },
  {
    id: '2',
    userId: 'user-1',
    roomId: 'room-2',
    rating: 3,
    summary: '장치는 좋았지만 스토리가 아쉬움',
    subMetrics: {
      puzzleQuality: 3,
      storyDirection: 2,
      setQuality: 5,
      horror: 4,
      puzzleDifficulty: 3,
      clearDifficulty: 4,
    },
    visitMeta: {
      isSuccess: false,
      remainingMinutes: null,
      headcount: 3,
      genreTags: ['공포', '스릴러'],
      customGenre: null,
      wouldRevisit: false,
    },
    visitedAt: '2026-02-10',
    body: '공포 연출은 최상급이지만 퍼즐 연결이 매끄럽지 않았다.',
    photos: [],
    visibility: 'group',
    shareToken: null,
    createdAt: '2026-02-10T14:30:00Z',
    updatedAt: '2026-02-10T14:30:00Z',
  },
  {
    id: '3',
    userId: 'user-1',
    roomId: 'room-3',
    rating: 5,
    summary: '역대급 테마, 무조건 추천',
    subMetrics: {
      puzzleQuality: 5,
      storyDirection: 5,
      setQuality: 5,
      horror: 1,
      puzzleDifficulty: 3,
      clearDifficulty: 2,
    },
    visitMeta: {
      isSuccess: true,
      remainingMinutes: 15,
      headcount: 2,
      genreTags: ['감성', '드라마', '판타지'],
      customGenre: null,
      wouldRevisit: true,
    },
    visitedAt: '2026-02-05',
    body: '감성 테마의 정점. 엔딩에서 소름이 돋았다.',
    photos: [],
    visibility: 'group',
    shareToken: null,
    createdAt: '2026-02-05T09:00:00Z',
    updatedAt: '2026-02-05T09:00:00Z',
  },
]
